# -*- coding: utf-8 -*-
"""X and Y to hdf5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w3mMw7iKEXn4lDQhag6oObLWMuhOB6HD
"""

!pip install deepdish

!pip3 install torch torchvision

import numpy as np
import random
import deepdish as dd
import string
import h5py
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, utils

N = 5
X = []
for i in range(0,N):
  rand = random.randint(0, 10)
  np_a = np.array([[rand for x in range(rand)] for y in range(rand)])
  X.append(np_a)  

Y = [''.join(random.choices(string.ascii_uppercase + string.digits, k=N*5)) for i in range(0, N)]
dd.io.save('test.h5', (X, Y))

print((X,Y))

recreation = dd.io.load('test.h5', '/')
recreation

len(recreation['data'][1])

class XY(Dataset):
    """X to Y dataset."""

    def __init__(self, hdf5_location):

        self.hdf5 = dd.io.load(hdf5_location, '/')['data']

    def __len__(self):
        return len(self.hdf5[1])

    def __getitem__(self, idx):
        return (self.hdf5[0][idx], self.hdf5[1][idx])

dataset = XY('test.h5')

len(dataset), dataset[3]

